name: MissileWarsX-Compatibility
version: ${project.version}
main: ca.encodeous.mwx.compatibility.MissileWarsXCompat
authors: [ Encodeous ]
depend:
  - MissileWarsX
loadbefore:
  - MissileWarsX
description: MissileWarsX Legacy Compatibility Plugin
commands:
#  Admin/Privileged Commands
  mwmake:
    description: Creates a missile from a selection
    usage: /<command> <pivot-x> <pivot-y> <pivot-z> <sel-x> <sel-y> <sel-z> <sel2-x> <sel2-y> <sel2-z> <missile-name>
    permission: mwx.admin
  mwteam:
    permission: mwx.admin
    description: Sets a player to a given team
    usage: /<command> <player-name> <red/green/spectator/lobby>
    aliases:
      - mwt
  mwpaste:
    description: Pastes a saved missile without updating at a certain location
    permission: mwx.admin
    usage: /<command> <pivot-x> <pivot-y> <pivot-z> <missile-name> <red/green>
  mwlaunch:
    description: Pastes a saved missile and updates it at a certain location
    permission: mwx.admin
    usage: /<command> <pivot-x> <pivot-y> <pivot-z> <missile-name> <red/green>
  mwfireball:
    description: Summons a fireball
    aliases:
      - mwf
    usage: /<command> <x> <y> <z>
  mwgive:
    description: Gives you the specified item
    aliases:
      - mwi
    usage: /<command> [player-name] <missile-wars-item-id/*> [count]
  start:
    description: Forcefully starts the game
    usage: /<command>
  reset:
    description: Forcefully restarts the game
    permission: mwx.admin
    aliases:
      - end
    usage: /<command>
  wipe:
    description: Forcefully wipes the current lobby map
    usage: /<command>
  gmc:
    description: Switch to creative mode
    aliases:
      - c
    usage: /<command>
  gms:
    description: Switch to survival mode
    aliases:
      - s
    usage: /<command>
  mwreload:
    description: Reloads the configuration file
    permission: mwx.admin
    usage: /<command>
  mwedit:
    description: Edit the missile wars template map, choose between the auto join or manual join map
    permission: mwx.admin
    usage: /<command> <auto/manual>
# Player commands
  lobby:
    description: Return to the current lobby, or switch between lobbies
    usage: /<command> [lobby-id]
    aliases:
      - l
      - mw
      - leave
  spectate:
    description: Spectate the game
    usage: /<command>
  ready:
    description: Signal that your team is ready in a ranked game
    usage: /<command>
  # Info commands
  mwitems:
    description: Lists all registered items
    usage: /<command>
  mwmissiles:
    description: Lists all registered missiles
    usage: /<command>
  ping:
    description: Gets your ping to the server
    usage: /<command>
  players:
    description: Gets a list of all online players
    usage: /<command>
    aliases:
      - online
      - p
      - glist
      - globallist
      - mwlist