name: MissileWarsX
version: ${project.version}
main: ca.encodeous.mwx.MissileWarsX
authors: [ Encodeous ]
depend:
  - ProtocolLib
  - FastAsyncWorldEdit
description: MissileWarsX - An open source implementation of the Legendary Missile Wars minigame
api-version: 1.13